
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


Traceback (most recent call last):
  File "/ibex/user/goux/project/traj_mu/traj_mu/3_1_SISA_Random_Sort_Shard_Sub_model_training.py", line 163, in <module>
    main()
  File "/ibex/user/goux/project/traj_mu/traj_mu/3_1_SISA_Random_Sort_Shard_Sub_model_training.py", line 127, in main
    source_data = pd.read_csv(csv_file)
  File "/home/goux/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/goux/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/goux/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/goux/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
  File "/home/goux/.local/lib/python3.9/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: './taxi_data_Singapore/3-Slidng_Windows_Data_Clustering_Clean.csv'
Traceback (most recent call last):
  File "/ibex/user/goux/project/traj_mu/traj_mu/3_2_SISA_Random_Sort_Shard_Loss_weight_training.py", line 196, in <module>
    main()
  File "/ibex/user/goux/project/traj_mu/traj_mu/3_2_SISA_Random_Sort_Shard_Loss_weight_training.py", line 158, in main
    source_data = pd.read_csv(csv_file)
  File "/home/goux/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/goux/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/goux/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/goux/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
  File "/home/goux/.local/lib/python3.9/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: './taxi_data_Singapore/3-Slidng_Windows_Data_Clustering_Clean.csv'
